/* generated by MKexpanded.sh */
#include <curses.priv.h>
#include <term.h>
#if NCURSES_EXPANDED
 void _nc_toggle_attr_on (attr_t *S, attr_t at)
{
        { if (PAIR_NUMBER(at) > 0) (*S) = ((*S) & ALL_BUT_COLOR) | (at); else (*S) |= (at); ;};
}
 void _nc_toggle_attr_off (attr_t *S, attr_t at)
{
        { if (FALSE == TRUE) { if (PAIR_NUMBER(at) == 0xff) (*S) &= ~(at); else (*S) &= ~((at)&ALL_BUT_COLOR); } else { if (PAIR_NUMBER(at) > 0x00) (*S) &= ~(at|((((1UL) << 8) - 1UL) << ((0) + 8))); else (*S) &= ~(at); } ;};
}
 int _nc_DelCharCost (int count)
{
        return ((cur_term->type. Strings[105] != 0) ? SP->_dch_cost : ((cur_term->type. Strings[21] != 0) ? (SP->_dch1_cost * count) : 1000000));
}
 int _nc_InsCharCost (int count)
{
        return ((cur_term->type. Strings[108] != 0) ? SP->_ich_cost : ((cur_term->type. Strings[31] && cur_term->type. Strings[42]) ? SP->_smir_cost + SP->_rmir_cost + (SP->_ip_cost * count) : ((cur_term->type. Strings[52] != 0) ? ((SP->_ich1_cost + SP->_ip_cost) * count) : 1000000)));
}
 void _nc_UpdateAttrs (chtype c)
{
        if (SP->_current_attr != (c)) vidattr((c));;
}
#else /* ! NCURSES_EXPANDED */
NCURSES_EXPORT(void) _nc_expanded (void) { }
#endif /* NCURSES_EXPANDED */
